repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0  
    hooks:
      - id: black
        name: black (auto-format)
        language_version: python
        files: ^ingest/  
        additional_dependencies: []

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (auto-format)
        language_version: python
        files: ^ingest/
        additional_dependencies: []
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: flake8 (check)
        language_version: python
        files: ^ingest/
        additional_dependencies: [flake8-bugbear]
        args: ["--max-line-length=120", "--extend-ignore=E203,W503,B008"]

  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.5
  #   hooks:
  #     - id: bandit
  #       name: bandit (security scan)
  #       language_version: python3.10
  #       files: ^ingest/
