services:
  airflow-db:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5
    volumes:
      - airflow-db:/var/lib/postgresql/data

  airflow-init:
    image: airflow-custom:2.9.2-python3.10
    depends_on:
      airflow-db:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_WEBSERVER_SECRET_KEY}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    entrypoint: |
      bash -c '
        echo "[INIT] Inicializando Airflow DB..." &&
        airflow db init &&
        airflow db migrate &&
        echo "[INIT] Creando usuario admin..." &&
        airflow users create \
            --username admin \
            --password admin \
            --firstname Air \
            --lastname Flow \
            --role Admin \
            --email admin@airflow.com || true
      '
    restart: "no"

  airflow-webserver:
    image: airflow-custom:2.9.2-python3.10
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_WEBSERVER_SECRET_KEY}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__SMTP__SMTP_HOST: smtp.mailgun.org
      AIRFLOW__SMTP__SMTP_STARTTLS: "true"
      AIRFLOW__SMTP__SMTP_SSL: "false"
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_USER: ${MAILGUN_SMTP_USER}
      AIRFLOW__SMTP__SMTP_PASSWORD: ${MAILGUN_SMTP_PASSWORD}
      AIRFLOW__SMTP__SMTP_MAIL_FROM: "dept01@sandbox4ed83056ba13482382a9000ad56cead7.mailgun.org"
    ports:
      - "8081:8080"
    command: webserver
    restart: always
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow_logs:/opt/airflow/logs

  airflow-scheduler:
    image: airflow-custom:2.9.2-python3.10
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_WEBSERVER_SECRET_KEY}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__SMTP__SMTP_HOST: smtp.mailgun.org
      AIRFLOW__SMTP__SMTP_STARTTLS: "true"
      AIRFLOW__SMTP__SMTP_SSL: "false"
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_USER: ""
      AIRFLOW__SMTP__SMTP_PASSWORD: ""
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ""
    command: scheduler
    restart: always
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow_logs:/opt/airflow/logs

volumes:
  airflow-db:
  airflow-logs:
