services:
  api:
    build: .
    image: hh-api:latest
    container_name: hh-api
    ports:
      - "8000:8000"
    env_file:
      - .env          # Solo local
    environment:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET
      - REDIS_HOST
      - REDIS_PORT
      - API_KEY
      - DEBUG
    volumes:
      - ./:/app
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: hh-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
