name: Deploy Transform

on:
  push:
    branches: [ main ]
    paths:
      - "transform/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t transform-app ./transform

      - name: Transfer image to EC2
        run: |
          docker save transform-app | bzip2 | \
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_TRANSFORM_KEY }}" ec2-user@${{ secrets.EC2_TRANSFORM_IP }} \
          'bunzip2 | docker load'

      - name: Restart container
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_TRANSFORM_KEY }}" ec2-user@${{ secrets.EC2_TRANSFORM_IP }} \
          'docker-compose -f /home/ec2-user/transform/docker-compose.prod.yml up -d'
